// ==================================================================================
// Running the microservice 
// ==================================================================================

== Running the microservice

UpdateCrewService works in conjunction with MainCrewService.

For UpdateCrewService, you'll need to set your specific values in the bootstrap.properties like
[source,role="no_copy"]
mongo.hostname=avl-mongo-1.fyre.ibm.com
mongo.port=27017
mongo.dbname=crewdb

== Utilizing the OpenAPI UI

[role='command']

Go to the http://HOST:PORT/openapi/ui/[^] URL to see the OpenAPI user interface (UI) that provides API documentation and a client to test the API endpoints that you create after you see a message similar to the following example:

[source,role="no_copy"]
----
CWWKZ0001I: Application UpdateCrewService started in 5.715 seconds.
----

**Try the Update operation**

From the OpenAPI UI, test the update operation at the `PUT /api/crew/{id}` endpoint, where the `{id}` parameter is the `\<<ID>>` that you saved from the create operation. Use the following code as the request body:

[role='command']
```
{
  "name": "Member1",
  "rank": "Captain",
  "crewID": "1"
}
```

This request updates the rank of the crew member that you created from `Officer` to `Captain`.

You'll receive a response that contains the JSON object of the updated crew member, as shown in the following example:

[role="no_copy"]
```
{
  "Name": "Member1",
  "Rank": "Captain",
  "CrewID": "1",
  "_id": {
    "$oid": "<<ID>>"
  }
}
```


